### ISSUE TITLE
Keep track of played songs instead of songs put in the queue (or both)

### ISSUE THREAD

**Issue by ysbrandB** [saproto/ProTube#101]
I think the statistic which songs actually got played is more usefull since users put in entire playlists when then get deleted when they leave the room. I suggest only adding the video to your history when it gets deleted from the queue or to add it as a statistic.

**Comment by Menkveld-24** [comment]
@ysbrandB Currently videos will only be added to the statistic if it has been fully played. Its not added to the statistics when the video is skipped or deleted from the queue
