### ISSUE TITLE
Take currently playing song into account for round-robin algorithm. 

### ISSUE THREAD

**Issue by Wilkuu-2** [saproto/ProTube#131]
Currently, the song that is playing isn't counted towards the round-robin. 
This creates situations where one person has two songs playing in a row when they add two songs before someone else adds a song.

**Comment by Menkveld-24** [comment]
https://github.com/saproto/ProTube/blob/588d1d5f0881f3a596fc1d16785ac702d446675e/server/modules/QueueManager.js#L121

**Comment by Menkveld-24** [comment]
Resolved in #132
