### ISSUE TITLE
Use the icons of te radio instead of the radio name, also put these icons in a grid

### ISSUE THREAD

**Issue by ysbrandB** [saproto/ProTube#19]
Just make a collapsable bar called radio, and when uncollapsed show a grid of their icons (probably 3-ish icons/rows underneath eachother?)

**Comment by Menkveld-24** [comment]
Added (partially) in: https://github.com/saproto/ProTube/commit/b16c2db2e3e4ea4d8a325c33ac4f1be64e9426f0
