### ISSUE TITLE
"requests full access your account" is not correct english, and a bit scary

### ISSUE THREAD

**Issue by ysbrandB** [saproto/ProTube#30]
The authorization on the Laravel site states 'requests full access your account', which misses at least a 'to' and sounds way scarier then it is.

**Comment by Menkveld-24** [comment]
Protube doesnt have anything to do with the display message I believe. 
see: 
https://github.com/saproto/saproto/blob/f5a081021db233949a794b3e66b24f7bef43b8bf/resources/views/vendor/passport/authorize.blade.php

**Comment by MaxLiebe** [comment]
As stated by Menke, this issue should be posted on the main repo.
