### ISSUE TITLE
Video titles get cut off if they're too long in the queue on the screen, which means you often can't see the song name.

### ISSUE THREAD

**Issue by MaxLiebe** [saproto/ProTube#68]
I believe this is especially annoying for the song that's currently playing.
Maybe make them scrollable? Or at least 2 lines high to account for most songs.
<img width="385" alt="image" src="https://user-images.githubusercontent.com/38863575/208051605-ddf209b1-542f-4c1b-b7ae-31f09b8a34df.png">

**Comment by Jessseee** [comment]
We could make the video title scroll if it is too long, so we can keep the consistent height of the queue cards.
